project_id = "lqspgspmympmulorcmsb"

[functions.generate-learning-path]
verify_jwt = false

[functions.analyze-artworks]
verify_jwt = false

[functions.analyze-collaboration]
verify_jwt = false

[functions.analyze-task-drawing]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.analyze-image-clip]
verify_jwt = false
